force-app/main/default/objects/Account/fields/PorcentajeAportaciones__c.field-meta.xml
<CustomField>
    <fullName>PorcentajeAportaciones__c</fullName>
    <inlineHelpText>% of commercial contributions signed by the Customer</inlineHelpText>
    <label>% Aportaciones</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/PorcentajeConvenio__c.field-meta.xml
<CustomField>
    <fullName>PorcentajeConvenio__c</fullName>
    <inlineHelpText>% of commercial agreement signed by the Customer</inlineHelpText>
    <label>% Convenio</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PlanificacionComercial__c.field-meta.xml
<CustomField>
    <fullName>PlanificacionComercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Planificación comercial</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PlanificacionComercial__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.CloseDate</field>
            <operation>greaterOrEqual</operation>
            <valueField>PlanificacionComercial__c.Inicio__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.CloseDate</field>
            <operation>lessOrEqual</operation>
            <valueField>PlanificacionComercial__c.Fin__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>PlanificacionComercial__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Aportaciones_2__c.field-meta.xml
<CustomField>
    <fullName>Aportaciones_2__c</fullName>
    <description>Guarda el valor de Opportunity.PlanificacionComercial__r.PorcentajeAportaciones__c cuando se crea o modifica un Item de Oportunidad</description>
    <label>% Aportaciones</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Convenio_2__c.field-meta.xml
<CustomField>
    <fullName>Convenio_2__c</fullName>
    <description>Guarda el valor de Opportunity.PlanificacionComercial__r.PorcentajeConvenio__c cuando se crea o modifica un Producto de Oportunidad</description>
    <label>% Convenio</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Modificar_precio_manual__c.field-meta.xml
<CustomField>
    <fullName>Modificar_precio_manual__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Modificar precio manual</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PlanificacionComercial__c/fields/PorcentajeAportaciones__c.field-meta.xml
<CustomField>
    <fullName>PorcentajeAportaciones__c</fullName>
    <label>% Aportaciones</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PlanificacionComercial__c/fields/PorcentajeConvenio__c.field-meta.xml
<CustomField>
    <fullName>PorcentajeConvenio__c</fullName>
    <label>% Convenio</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

tmp_p2/objects/Product2/fields/Clase__c.field-meta.xml
<CustomField>
    <fullName>Clase__c</fullName>
    <label>Clase</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Subfamilia__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01-Accent Chairs</fullName>
            </value>
            <value>
                <fullName>02-Coffee &amp; Side &amp; End Tables</fullName>
            </value>
            <value>
                <fullName>03-Sofas &amp; Couches</fullName>
            </value>
            <value>
                <fullName>04-Sectional Sofas</fullName>
            </value>
            <value>
                <fullName>05-Loveseats</fullName>
            </value>
            <value>
                <fullName>06-Sofa Beds</fullName>
            </value>
            <value>
                <fullName>07-Benches &amp; Ottomans</fullName>
            </value>
            <value>
                <fullName>08-Recliners</fullName>
            </value>
            <value>
                <fullName>09-Console Tables &amp; Sideboards</fullName>
            </value>
            <value>
                <fullName>10-Tv Stands &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>11-Storage Furniture</fullName>
            </value>
            <value>
                <fullName>01-Dining Chairs</fullName>
            </value>
            <value>
                <fullName>02-Dining Tables</fullName>
            </value>
            <value>
                <fullName>03-Dining Sets</fullName>
            </value>
            <value>
                <fullName>04-Bar Stools</fullName>
            </value>
            <value>
                <fullName>05-Kitchen Carts &amp; Islands</fullName>
            </value>
            <value>
                <fullName>06-Dining Storage</fullName>
            </value>
            <value>
                <fullName>01-Office Chairs</fullName>
            </value>
            <value>
                <fullName>02-Desks</fullName>
            </value>
            <value>
                <fullName>03-Bookcases</fullName>
            </value>
            <value>
                <fullName>04-Office Storage</fullName>
            </value>
            <value>
                <fullName>01-Closet Storage</fullName>
            </value>
            <value>
                <fullName>02-Shoe Storage</fullName>
            </value>
            <value>
                <fullName>03-Storage Carts &amp; Drawers</fullName>
            </value>
            <value>
                <fullName>04-Storage Bins &amp; Boxes</fullName>
            </value>
            <value>
                <fullName>05-Shelving Units</fullName>
            </value>
            <value>
                <fullName>01-Outdoor Dining Sets</fullName>
            </value>
            <value>
                <fullName>02-Outdoor Seating Sets</fullName>
            </value>
            <value>
                <fullName>03-Outdoor Chairs &amp; Loungers</fullName>
            </value>
            <value>
                <fullName>04-Outdoor Tables</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

tmp_p2/objects/Product2/fields/Familia_producto_base__c.field-meta.xml
<CustomField>
    <fullName>Familia_producto_base__c</fullName>
    <formula>IF(ISBLANK(ProductoBase__c), TEXT(Family), TEXT(ProductoBase__r.Family))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Familia producto base</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca_base</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A-!DEA Garden</fullName>
            </value>
            <value>
                <fullName>AR-ARO (MAKRO ARGENTINA)</fullName>
            </value>
            <value>
                <fullName>B-!DEA Home</fullName>
            </value>
            <value>
                <fullName>C-!DEA Heating &amp; Fan</fullName>
            </value>
            <value>
                <fullName>D-DO BRANDS</fullName>
            </value>
            <value>
                <fullName>E-MEMBERS CHOICE (CITY CLUB)</fullName>
            </value>
            <value>
                <fullName>F-ALLURE (DO BRANDS CITY CLUB)</fullName>
            </value>
            <value>
                <fullName>G-B2COOL (DO BRANDS - CITY CLUB)</fullName>
            </value>
            <value>
                <fullName>H-OUTDOOR TREND (SORIANA)</fullName>
            </value>
            <value>
                <fullName>HE-HEUMAN BRAND (LIVERPOOL)</fullName>
            </value>
            <value>
                <fullName>HL-HOME LINE (CHEDRAUI)</fullName>
            </value>
            <value>
                <fullName>I-HOMESTYLE DESIGN (SORIANA)</fullName>
            </value>
            <value>
                <fullName>J-ROOTS (CENCOSUD)</fullName>
            </value>
            <value>
                <fullName>K-BSAFE (AFALPI)</fullName>
            </value>
            <value>
                <fullName>KE-KERRVILLE (HEB)</fullName>
            </value>
            <value>
                <fullName>KO-KOVA (KOVA FURNITURE)</fullName>
            </value>
            <value>
                <fullName>L-LIVING ACCENTS (ACE)</fullName>
            </value>
            <value>
                <fullName>M-MEMBERS MARK (SAMS)</fullName>
            </value>
            <value>
                <fullName>N-TALA 18 (AFALPI)</fullName>
            </value>
            <value>
                <fullName>O-KREA (CENCOSUD)</fullName>
            </value>
            <value>
                <fullName>OS-OUTDOOR SOLUTIONS (HEB)</fullName>
            </value>
            <value>
                <fullName>P-CLARK GARDEN (HOMESENTRY)</fullName>
            </value>
            <value>
                <fullName>Q-SUNABLE (SAMS)</fullName>
            </value>
            <value>
                <fullName>R-CARREFOUR HOME (CARREFOUR)</fullName>
            </value>
            <value>
                <fullName>S-RED DOT (CASA LEY)</fullName>
            </value>
            <value>
                <fullName>ST-STUK (OFFICE MAX)</fullName>
                <default>true</default>
                <label>ST-STUK (OFFICE MAX)</label>
            </value>
            <value>
                <fullName>T-MAHAIA (LA COMER)</fullName>
            </value>
            <value>
                <fullName>U-MASTER CRAFT (SORIANA)</fullName>
            </value>
            <value>
                <fullName>V-VARIOS ESPECIALES</fullName>
            </value>
            <value>
                <fullName>VI-VIOS (SORIANA)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductExtensionController.cls
public class ProductExtensionController
{
    public static final String KEY_ACC = 'Key Account';

    public ApexPages.StandardSetController stdCon{get; set;}
    
    // List of products that we get with a query
    private List<Product2> productList;
    
    // Map of products selected with checkbox
    private Map<Id, Boolean> checkedProducts;
    
    // List of full products selected
    private Map<Id, Product2> selectedProducts; 
    
    public String prodSearch {get;set;}
    
    //flags to enable or disable output panel in UI
    public Boolean isEditEnabled {get;set;}
    public Boolean isSearchEnabled {get;set;}
    
    public String idSelectedProd {get;set;}
    
    public String selectedPricebook {get;set;}
    
    private List<OpportunityProductHybrid> hybridProds;
    
    private String opportunityId;
    
    private Opportunity opp;
    
    /*
     *  Initializes the page with a list of 300 products. This limit was applied to avoid viewstate error.
     *  The limit won't affect the operations, since sales executives use keyword search to find the products 
     *  and we don't apply the limit there.
     */
    public ProductExtensionController(ApexPages.StandardController controller) {
        opportunityId = controller.getId();

        opp = [SELECT Id, 
                      Pricebook2Id, 
                      PlanificacionComercial__r.PorcentajeAportaciones__c, 
                      PlanificacionComercial__r.PorcentajeConvenio__c,
                      CurrencyISOCode 
                 FROM Opportunity 
                WHERE Id = :opportunityId];
  
        selectedProducts = new Map<Id, Product2>();
        
        productList = [SELECT Id, 
                            Name,
                            Description, 
                            Thumb1__c, 
                            CodigoDeProductoBase__c, 
                            ProductoBase__r.Marca__c, 
                            Familia_producto_base__c, 
                            Subfamilia__c, 
                            Clase__c,
                            ProductoBase__r.Subfamilia__c,
                            ProductoBase__r.Clase__c,
                            IsActive
                            FROM Product2
                            WHERE IsActive = true
                            AND Id IN (SELECT Product2Id FROM PricebookEntry WHERE CurrencyISOCode = :opp.CurrencyISOCode)
                            ORDER BY Name
                            LIMIT 300];

        checkedProducts = new Map<Id, Boolean>();
        convertMapToList(productList, checkedProducts);
        
        stdCon = new ApexPages.StandardSetController(productList);
        stdCon.setPageSize(20);
        
        //KEY ACCOUNT PRICEBOOK MUST EXIST SO NOT CHECKING FOR NULLS HERE
        //NEEDS TO BE UPDATED ONCE WE ADD DIFF PRICEBOOKS FOR DIFF INCOTERMS
        List<Pricebook2> keyAccount = [SELECT Id, 
                                            Name 
                                            FROM Pricebook2
                                            WHERE Name = :KEY_ACC];
        
        isSearchEnabled = true;
        isEditEnabled = false;
        selectedPricebook = keyAccount[0].Id;
    }

    
    public List<Product2> getProductList()
    {
         List<Product2> lista;  
         if(stdCon != null)
         {
             System.debug('GET PL Standard Set Controller size[' + stdCon.getResultSize() + ']');
             lista = (List<Product2>)stdCon.getRecords();
             System.debug('GET PL Standard Set Controller size[' + lista.size() + ']');
             return (List<Product2>)stdCon.getRecords(); 
         }
         else
         {
             productList = new List<Product2>();
             return productList; 
         }
    }
 
    
    // Dropdown filters (exact match, combined with AND)
    public String selPGCode {get;set;}
    public String selBrand {get;set;}
    public String selFamily {get;set;}
    public String selSubfamily {get;set;}
    public String selClass {get;set;}

    public List<SelectOption> getBrandOptions() { return picklistOptions(Product2.Marca__c.getDescribe()); }
    public List<SelectOption> getFamilyOptions() { return picklistOptions(Product2.Family.getDescribe()); }
    public List<SelectOption> getSubfamilyOptions() { return picklistOptions(Product2.Subfamilia__c.getDescribe(), Product2.Family.getDescribe(), selFamily); }
    public List<SelectOption> getClassOptions() { return picklistOptions(Product2.Clase__c.getDescribe(), Product2.Subfamilia__c.getDescribe(), selSubfamily); }

    private List<SelectOption> picklistOptions(Schema.DescribeFieldResult f)
    {
        return picklistOptions(f, null, null);
    }

    // Active values of f; if ctrlValue is set, only those valid for it per the field dependency (validFor bitmap)
    private List<SelectOption> picklistOptions(Schema.DescribeFieldResult f, Schema.DescribeFieldResult ctrl, String ctrlValue)
    {
        Integer idx = -1;
        if(String.isNotBlank(ctrlValue))
        {
            List<Schema.PicklistEntry> ctrlValues = ctrl.getPicklistValues();
            for(Integer i = 0; i < ctrlValues.size(); i++)
            {
                if(ctrlValues[i].getValue().equals(ctrlValue)) idx = i;
            }
        }
        List<SelectOption> opts = new List<SelectOption>{ new SelectOption('', '-- All --') };
        for(Schema.PicklistEntry pe : f.getPicklistValues())
        {
            if(!pe.isActive()) continue;
            if(String.isNotBlank(ctrlValue) && !isValidFor(pe, idx)) continue;
            opts.add(new SelectOption(pe.getValue(), pe.getLabel()));
        }
        return opts;
    }

    private static Boolean isValidFor(Schema.PicklistEntry pe, Integer idx)
    {
        if(idx < 0) return false;
        String validFor = (String)((Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(pe))).get('validFor');
        if(String.isBlank(validFor)) return false;
        String hex = EncodingUtil.convertToHex(EncodingUtil.base64Decode(validFor));
        if(idx / 4 >= hex.length()) return false;
        Integer nibble = '0123456789abcdef'.indexOf(hex.substring(idx / 4, idx / 4 + 1));
        Integer mask = 8 >> Math.mod(idx, 4);
        return (nibble & mask) != 0;
    }

    public void familyChanged()
    {
        selSubfamily = selClass = null;
        searchProducts();
    }

    public void subfamilyChanged()
    {
        selClass = null;
        searchProducts();
    }

    // Distinct PG Codes of the searchable products, used by the PG Code datalist (type-ahead)
    public List<String> getPGCodes()
    {
        Set<String> codes = new Set<String>();
        for(Product2 p : [SELECT CodigoDeProductoBase__c FROM Product2
                          WHERE IsActive = true
                          AND Id IN (SELECT Product2Id FROM PricebookEntry WHERE CurrencyISOCode = :opp.CurrencyISOCode)])
        {
            if(String.isNotBlank(p.CodigoDeProductoBase__c)) codes.add(p.CodigoDeProductoBase__c);
        }
        List<String> sorted = new List<String>(codes);
        sorted.sort();
        return sorted;
    }

    public void clearFilters()
    {
        prodSearch = selPGCode = selBrand = selFamily = selSubfamily = selClass = null;
        searchProducts();
    }

    private static String eqFilter(String field, String value)
    {
        return String.isBlank(value) ? '' : ' AND ' + field + ' = \'' + String.escapeSingleQuotes(value.trim()) + '\'';
    }

    public void searchProducts()
    {
        String query, strFilter;

        if(prodSearch != null && (prodSearch).trim() !='')
        {
            String term = String.escapeSingleQuotes(prodSearch.trim());
            strFilter = '((';
            Integer i = 0;
            for(String s : term.split(' ')){
                if(i > 0){
                    strFilter += ' AND ';
                }
                strFilter += '(Name Like \'%' + s + '%\' OR Familia_producto_base__c Like \'%' + s + '%\' OR ProductoBase__r.Subfamilia__c Like \'%' + s + '%\' OR ProductoBase__r.Clase__c Like \'%' + s + '%\')';
                i++;
            }
            strFilter += ') OR CodigoDeProductoBase__c Like \'%' + term + '%\' OR ProductoBase__r.Marca__c Like \'%' + term + '%\')';

        }

        query = 'SELECT Id, Name, Description, Thumb1__c, CodigoDeProductoBase__c, ProductoBase__r.Marca__c,'
                + ' Familia_producto_base__c, Subfamilia__c, Clase__c, ProductoBase__r.Subfamilia__c, ProductoBase__r.Clase__c,'
                + ' IsActive FROM Product2 WHERE IsActive = true'
                + ' AND Id IN (SELECT Product2Id FROM PricebookEntry WHERE CurrencyISOCode = \'' + opp.CurrencyISOCode +'\')';

        if(strFilter != null)
        {
            query += ' AND ' + strFilter;
        }
        query += eqFilter('CodigoDeProductoBase__c', selPGCode)
               + eqFilter('ProductoBase__r.Marca__c', selBrand)
               + eqFilter('Familia_producto_base__c', selFamily)
               + eqFilter('ProductoBase__r.Subfamilia__c', selSubfamily)
               + eqFilter('ProductoBase__r.Clase__c', selClass);
        query += ' ORDER BY Name LIMIT 300';

        system.debug('QUERY > ' + query + ' < ');
        productList = Database.query(query);
        convertMapToList(productList, checkedProducts);
        
        Product2 preSelected = null;
        for(Product2 pr : productList)
        {
            preSelected = selectedProducts.get(pr.id);
            if(preSelected != null)
            {
                checkedProducts.put(pr.id, true);
            }
        }
        
        stdCon = new ApexPages.StandardSetController(productList);            
        stdCon.setPageSize(20);
    }
    
    
    public Boolean hasNext 
    { 
        get 
        { 
            if(stdCon != null)
            {
                return stdCon.getHasNext(); 
            }
            return false;
            
        } 
        set; 
    } 

    public Boolean hasPrevious 
    { 
        get 
        { 
            if(stdCon != null)
            {
                return stdCon.getHasPrevious(); 
            }
            return false;
        } 
        set; 
    } 

    public Integer pageNumber 
    { 
        get 
        { 
            if(stdCon != null)
            {
               return stdCon.getPageNumber(); 
            }
            return 0;
        } 
        set; 
    } 

    public void previous() 
    { 
        if(stdCon != null)
        {
            stdCon.previous(); 
        }
    } 

    public void next() 
    { 
        if(stdCon != null)
        {
           stdCon.next(); 
        }
    } 
    
    public Integer getResultSize()
    {
        if(stdCon != null)
        {
           return stdCon.getResultSize();
        }
        return 0;
    }
    
 
    public Map<Id, Boolean> getCheckedProducts()
    {
        return checkedProducts;
    }  
    
    
    public void clickProduct()
    {
        Product2 prod;
        String param = Apexpages.currentPage().getParameters().get('idProd');
        Boolean value;
      
        String idp = param;
      
        value = checkedProducts.get(idp);
        if(value)
        {
            prod = findProductById(idp);
            if(prod != null)
            {
                selectedProducts.put(idp, prod);
            }
        }
        else
        {
            //if exist in selected products
            prod = selectedProducts.get(idp);
            if(prod != null)
            {
                //remove              
                selectedProducts.remove(idp);
            }
        }
    }
    
    public void clickDeleteSelectedProduct()
    {
        String prodId = null;
        //String[] tokens = null;
        Product2 prod;
        String param = Apexpages.currentPage().getParameters().get('idProdDel');
        if(idSelectedProd != null)
        {
            prodId = idSelectedProd;
                
            //if exist in selected products
            prod = selectedProducts.get(prodId);
            if(prod != null)
            {
                //remove      
                selectedProducts.remove(prodId);
            }
            checkedProducts.put(prodId, false);
        }
    }
    
    
    public Product2 findProductById(String id)
    {
        if(productList != null)
        {
          for(Product2 prod : productList)
          {
              if(prod.id.equals(id))
              {
                  return prod;
              }
          }
        }
        return null;
    }
    
    public List<Product2> getSelectedProducts()
    {
       List<Product2> listToDisplay = new List<Product2>();
       Product2 value = null;
       for(String idp : selectedProducts.keySet())
       {
           value = selectedProducts.get(idp);
           listToDisplay.add(value);
       }
       return listToDisplay;
    }
    

    public PageReference nextPage()
    {
        isSearchEnabled = false;
        isEditEnabled = true;        
        
        setupListHybridProducts();
        
        return null;
    }


    public PageReference previousPage()
    {
        isSearchEnabled = true;
        isEditEnabled = false;        
        return null;
    }

    
    /**
     * This method is used in UI in order to setup a map associated to checkboxes 
     */
    private void convertMapToList(List<Product2> listProducts, Map<Id, Boolean> checkedProducts)
    {
       for(Product2 p : productList)
       {
           checkedProducts.put(p.Id, false);
       }
    }
    
    
    /*
     * 
     */    
    public class OpportunityProductHybrid
    {
        public Opportunity oppHybridProd;
        public OpportunityLineItem item {get;set;}
        public Product2 product {get;set;}
        public Decimal priceWDisc {get;set;}
        
        public OpportunityProductHybrid(Id oppId, PricebookEntry pbe, Opportunity opp)
        {
            oppHybridProd = opp;
            
            item = new OpportunityLineItem(OpportunityId = oppId,
                                           PricebookEntryId = pbe.Id,
                                           Quantity = null,
                                           UnitPrice = calculateUnitPrice(pbe.UnitPrice).setScale(2),
                                           Aportaciones_2__c = oppHybridProd.PlanificacionComercial__r.PorcentajeAportaciones__c,
                                           Convenio_2__c = oppHybridProd.PlanificacionComercial__r.PorcentajeConvenio__c);
            priceWDisc = item.UnitPrice;
            product = pbe.Product2; 
        }
        
        
        /**
         * 
         */
        private Decimal calculateUnitPrice(Decimal unitPrice)
        {
           Decimal finalUnitPrice;
           finalUnitPrice = unitPrice / ( 1 - ((oppHybridProd.PlanificacionComercial__r.PorcentajeAportaciones__c + oppHybridProd.PlanificacionComercial__r.PorcentajeConvenio__c)/100));
           return finalUnitPrice;
        }
    }
    
    private void setupListHybridProducts()
    {
        List<PricebookEntry> listPriceBookEntry = null;
        List<String> idsProduct = new List<String>();
        Product2 prod;
        
        OpportunityProductHybrid hybridProd;

        for(String idp : selectedProducts.keySet())
        {
            idsProduct.add(idp);
        }

        listPriceBookEntry = [SELECT Id, 
                                     UnitPrice,
                                     Product2.Id,
                                     Product2.Name,
                                     Product2.Description, 
                                     Product2.Thumb1__c, 
                                     Product2.CodigoDeProductoBase__c, 
                                     Product2.ProductoBase__r.Marca__c, 
                                     Product2.Familia_producto_base__c, 
                                     Product2.Subfamilia__c, 
                                     Product2.Clase__c, 
                                     Product2.IsActive 
                                FROM PricebookEntry 
                               WHERE Pricebook2Id = :selectedPricebook 
                                 AND Product2Id IN :idsProduct
                                 AND CurrencyISOCode = :opp.CurrencyISOCode
                                 ORDER BY Product2.Name];

        PriceBook2 priceBook = [SELECT Id, Name from Pricebook2 WHERE Id =:selectedPricebook ];
        
        hybridProds = new List<OpportunityProductHybrid>();
        
        for(PriceBookEntry pbe : listPriceBookEntry)
        {
            hybridProd = new OpportunityProductHybrid(opportunityId, pbe, opp);
            hybridProds.add(hybridProd );
        }
    }
    
    public List<OpportunityProductHybrid> getHybridProducts()
    {
        return hybridProds;
    }
    
    
    public void  saveOppLineItem()
    {
        if(opp.Pricebook2Id == null) {
            opp.Pricebook2Id = selectedPricebook;
            update opp;
        }
        String retUrl;    
        List<OpportunityLineItem> oppList = new List<OpportunityLineItem>();
        for(OpportunityProductHybrid hp : hybridProds)
        {
            if(hp.priceWDisc != hp.item.UnitPrice){
                hp.item.Modificar_precio_manual__c = true;
            }
            oppList.add(hp.item);
        }
        
        try
        {
            insert oppList;
        }
        catch(DmlException e)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getDMLMessage(0)));
        }
    }

    public Boolean hasError { 
        get { 
            return ApexPages.hasMessages();
        }       
    }
    
}